name: privateclinicmanageproject 

services:
  mysql:
    image: davidd071003/privateclinicmanagerepository:database
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: privateclinicmanage
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
   
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network3

networks:
  app-network3:

volumes:
  db_data: {}
