FROM openjdk:19
COPY target/privateClinicManage-0.0.1-SNAPSHOT.jar privateClinicManage-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/privateClinicManage-0.0.1-SNAPSHOT.jar"]
# build new image from Dockerfile for backend